"""create quote

Revision ID: e91d113ed161
Revises: 78ba13627e4a
Create Date: 2024-10-31 00:33:35.015681

"""

import sqlalchemy as sa
from alembic import op

revision = "e91d113ed161"
down_revision = "78ba13627e4a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "author",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_author_name"), "author", ["name"], unique=True)
    op.create_table(
        "collection",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("emote", sa.String(), nullable=True),
        sa.Column("visibility", sa.Enum("PUBLIC", "PRIVATE", name="visibility"), nullable=False),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_collection_description"), "collection", ["description"], unique=False)
    op.create_index(op.f("ix_collection_emote"), "collection", ["emote"], unique=False)
    op.create_index(op.f("ix_collection_name"), "collection", ["name"], unique=False)
    op.create_index(op.f("ix_collection_visibility"), "collection", ["visibility"], unique=False)
    op.create_table(
        "quote",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=True),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["author.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_quote_content"), "quote", ["content"], unique=False)
    op.create_table(
        "quote_collection",
        sa.Column("quote_id", sa.Integer(), nullable=False),
        sa.Column("collection_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["collection_id"], ["collection.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["quote_id"], ["quote.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("quote_id", "collection_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("quote_collection")
    op.drop_index(op.f("ix_quote_content"), table_name="quote")
    op.drop_table("quote")
    op.drop_index(op.f("ix_collection_visibility"), table_name="collection")
    op.drop_index(op.f("ix_collection_name"), table_name="collection")
    op.drop_index(op.f("ix_collection_emote"), table_name="collection")
    op.drop_index(op.f("ix_collection_description"), table_name="collection")
    op.drop_table("collection")
    op.drop_index(op.f("ix_author_name"), table_name="author")
    op.drop_table("author")
    # ### end Alembic commands ###
