"""add created by user to author

Revision ID: eab156cea140
Revises: e91d113ed161
Create Date: 2024-10-31 18:45:27.957478

"""

import sqlalchemy as sa
from alembic import op

revision = "eab156cea140"
down_revision = "e91d113ed161"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("author", sa.Column("created_by_user_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_author_created_by_user", "author", "user", ["created_by_user_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_author_created_by_user", "author", type_="foreignkey")
    op.drop_column("author", "created_by_user_id")
    # ### end Alembic commands ###
